### ISSUE TITLE
About test.py

### ISSUE THREAD

**Issue by LLMOON** [AmeryXiong/MixDehazeNet#11]
作者您好，请问使用下载好的预训练模型可以直接用来test吗

我按照[DehazeFormer]类似的命令运行test.py，一直显示出错，具体如下：
python test.py --model MixDehazeNet-l --dataset Haze4k --exp haze4k

Traceback (most recent call last):
  File "test.py", line 94, in &lt;module&gt;
    network = eval(args.model.replace('-', '_'))()
  File "&lt;string&gt;", line 1, in &lt;module&gt;
NameError: name 'MixDehazeNet_l' is not defined

感谢您的解答

**Comment by AmeryXiong** [comment]
1.可以直接运行的，你要修改models/__init__.py的模型导入的名称。
2.如果使用Pycharm而不是命令行来运行代码，会方便一些。
________________________________
发件人: LLMOON ***@***.***>
发送时间: 2024年3月1日 11:59
收件人: AmeryXiong/MixDehazeNet ***@***.***>
抄送: Subscribed ***@***.***>
主题: [AmeryXiong/MixDehazeNet] About test.py (Issue #11)


作者您好，请问使用下载好的预训练模型可以直接用来test吗

我按照[DehazeFormer]类似的命令运行test.py，一直显示出错，具体如下：
python test.py --model MixDehazeNet-l --dataset Haze4k --exp haze4k

Traceback (most recent call last):
File "test.py", line 94, in <module>
network = eval(args.model.replace('-', '_'))()
File "<string>", line 1, in <module>
NameError: name 'MixDehazeNet_l' is not defined

感谢您的解答

―

**Comment by LLMOON** [comment]
理解了，谢谢您的回复
