### ISSUE TITLE
关于test.py

### ISSUE THREAD

**Issue by xujinxiaolaji** [AmeryXiong/MixDehazeNet#16]
大佬您好，
关于运行test.py时遇到问题：
==> Start testing, current model name: MixDehazeNet-s
[ WARN:0@3.728] global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_10.png'): can't open/read file: check file path/integrity
[ WARN:0@3.728] global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_1.png'): can't open/read file: check file path/integrity
[ WARN:0@3.729] global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_2.png'): can't open/read file: check file path/integrity
[ WARN:0@3.729] global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_3.png'): can't open/read file: check file path/integrity
[ WARN:0@3.729] global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_4.png'): can't open/read file: check file path/integrity
[ WARN:0@3.730] global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_7.png'): can't open/read file: check file path/integrity
[ WARN:0@3.730] global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_5.png'): can't open/read file: check file path/integrity
[ WARN:0@3.730] global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_6.png'): can't open/read file: check file path/integrity
[ WARN:0@3.730] global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_9.png'): can't open/read file: check file path/integrity
[ WARN:0@3.730] global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_8.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "test.py", line 118, in <module>
[ WARN:0@3.731] global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1401_6.png'): can't open/read file: check file path/integrity
[ WARN:0@3.731] global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1401_2.png'): can't open/read file: check file path/integrity
[ WARN:0@3.731] global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1401_5.png'): can't open/read file: check file path/integrity
我尝试绝对路径、检查文件权限，都没问题，仍然会报这个错误，可以麻烦您帮我解答一下吗，谢谢！

**Comment by AmeryXiong** [comment]
你好，根据报错，这可能是路径问题或者权限问题，要不使用绝对路径？

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: xujinxiaolaji ***@***.***>
Sent: Thursday, August 8, 2024 5:15:08 PM
To: AmeryXiong/MixDehazeNet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AmeryXiong/MixDehazeNet] 关于test.py (Issue #16)


大佬您好，
关于运行test.py时遇到问题：
==> Start testing, current model name: MixDehazeNet-s
[ ***@***.*** global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_10.png'): can't open/read file: check file path/integrity
[ ***@***.*** global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_1.png'): can't open/read file: check file path/integrity
[ ***@***.*** global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_2.png'): can't open/read file: check file path/integrity
[ ***@***.*** global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_3.png'): can't open/read file: check file path/integrity
[ ***@***.*** global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_4.png'): can't open/read file: check file path/integrity
[ ***@***.*** global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_7.png'): can't open/read file: check file path/integrity
[ ***@***.*** global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_5.png'): can't open/read file: check file path/integrity
[ ***@***.*** global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_6.png'): can't open/read file: check file path/integrity
[ ***@***.*** global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_9.png'): can't open/read file: check file path/integrity
[ ***@***.*** global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1400_8.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
File "test.py", line 118, in
[ ***@***.*** global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1401_6.png'): can't open/read file: check file path/integrity
[ ***@***.*** global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1401_2.png'): can't open/read file: check file path/integrity
[ ***@***.*** global loadsave.cpp:241 findDecoder imread_('./data/RESIDE-IN/test/hazy/1401_5.png'): can't open/read file: check file path/integrity
我尝试绝对路径、检查文件权限，都没问题，仍然会报这个错误，可以麻烦您帮我解答一下吗，谢谢！

―

**Comment by xujinxiaolaji** [comment]
大佬你好，我尝试了绝对路径还是一样的错误，我甚至换了台服务器，也还是这个错误

**Comment by xujinxiaolaji** [comment]
你好，大佬，我调试了一下代码，发现问题出在这里：dataset/loader.py的76行，source_img = read_img(os.path.join(self.root_dir, 'hazy', img_name)) * 2 - 1；以RESIDE-IN数据集为例，这行代码中的img_name假设是RESIDE/test/GT/1400.png，source_img这里读的是RESIDE-IN/test/hazy/1400.png 所以读不到。
所以这里您代码是能够正常读到/hazy/1400_1.png吗？

**Comment by AmeryXiong** [comment]
会不会是你的测试代码中数据库名称有问题，例如测试的数据集名称填错了。

可以根据断点调试的结果来反推一下，看看哪个配置参数的名称填写错误了。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by xujinxiaolaji** [comment]
大佬，我改了两行datasets/loader.py 修改了两行，能够正常运行了，但是我用MixDehazeNet-s，测SOTS-outdoor，PSNR有38.97呢
![Uploading 1723163832139.jpg…]()
