### ISSUE TITLE
数据读取

### ISSUE THREAD

**Issue by liu0619** [AmeryXiong/MixDehazeNet#2]
/home/lyl/MixDehazeNet-main/MixDehazeNet/data/outdoor/train/hazy/68553.jpg
    loss = train(train_loader, network, criterion, optimizer, scaler)
  File "/home/lyl/MixDehazeNet-main/MixDehazeNet/train.py", line 41, in train
    for batch in train_loader:
  File "/home/fang/anaconda3/envs/lyl/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/fang/anaconda3/envs/lyl/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1179, in _next_data
    return self._process_data(data)
  File "/home/fang/anaconda3/envs/lyl/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/fang/anaconda3/envs/lyl/lib/python3.6/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/fang/anaconda3/envs/lyl/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/fang/anaconda3/envs/lyl/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/fang/anaconda3/envs/lyl/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lyl/MixDehazeNet-main/MixDehazeNet/datasets/loader.py", line 78, in __getitem__
    source_img = read_img(os.path.join(self.root_dir, 'hazy', img_name)) * 2 - 1
  File "/home/lyl/MixDehazeNet-main/MixDehazeNet/datasets/common.py", line 50, in read_img
    return img[:, :, ::-1].astype('float32') / 255.0
TypeError: 'NoneType' object is not subscriptable
您好，这行一直报错，但是已经检查过数据路径没有问题，这是什么原因呢？

**Comment by AmeryXiong** [comment]
我最近两天会检查代码，之前一直比较忙。

**Comment by AlvinMLee** [comment]
您好，解决了吗

**Comment by AmeryXiong** [comment]
[你们好，这个错误已经知道原因了，是因为我的代码主要参考DehazeFormer，DehazeFormer数据集中图片名称是经过修改的，你们可以去DehazeFormer下载数据集，这样就不会运行出错。](https://github.com/IDKiro/DehazeFormer)

**Comment by AmeryXiong** [comment]
具体可以参考刚才更新的readme.
